name: Update Daily Phrase

on:
  schedule:
    - cron: '0 0 * * *' # Ejecuta el script a la medianoche (UTC) todos los días
  workflow_dispatch:

jobs:
  update-phrase:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install --upgrade pip

    - name: Run update script
      run: python scripts/update_quote.py

    - name: Commit and push changes
      run: |
        git config --global user.email 'Jvbass@users.noreply.github.com'
        git config --global user.name 'Jvbass'
        git add index.html
        git commit -m "Update daily phrase $(date)"
        git push
